<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net471</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>InvestmentPortfolio</RootNamespace>
    <AssemblyName>InvestmentPortfolio</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
